const fakeRatioLabels = {
  assetTurnoverTTM: 'Asset Turnover (TTM)',
  bookValueShareMRQ: 'Book Value Share (MRQ)',
  cashFlowShareTTM: 'Cash Flow Share (TTM)',
  cashShareMRQ: 'Cash Share (MRQ)',
  country: 'Country',
  createdAt: 'Created At',
  currentRatioRate: 'Current Ratio',
  debtToEquityRate: 'Debt to Equity Rate',
  dilutedEPSANN: 'Diluted EPS (Annual)',
  dividendGrowthRateANN: 'Dividend Growth Rate (Annual)',
  dividendYield5YearAvg5YA: 'Dividend Yield (5-Year Avg)',
  ePSMRQvsQtr1YrAgoMRQ: 'EPS (MRQ vs 1 Yr Ago MRQ)',
  ePSTTMvsTTM1YrAgoTTM: 'EPS (TTM vs 1 Yr Ago TTM)',
  earningsPerShareRate: 'Earnings Per Share Rate',
  grossMargin5YA: 'Gross Margin (5-Year Avg)',
  grossMarginRate: 'Gross Margin Rate',
  inventoryTurnoverTTM: 'Inventory Turnover (TTM)',
  lTDebtToEquityMRQ: 'Long-Term Debt to Equity (MRQ)',
  markSet: 'Market Set',
  netIncomeEmployeeTTM: 'Net Income per Employee (TTM)',
  netProfitMargin5YA: 'Net Profit Margin (5-Year Avg)',
  netProfitMarginRate: 'Net Profit Margin Rate',
  operatingMargin5YA: 'Operating Margin (5-Year Avg)',
  operatingMarginRate: 'Operating Margin Rate',
  payoutRatioTTM: 'Payout Ratio (TTM)',
  pretaxMargin5YA: 'Pretax Margin (5-Year Avg)',
  pretaxMarginTTM: 'Pretax Margin (TTM)',
  priceToBookRate: 'Price to Book Rate',
  priceToCashFlowMRQ: 'Price to Cash Flow (MRQ)',
  priceToEarningRate: 'Price to Earnings Rate',
  priceToFreeCashFlowTTM: 'Price to Free Cash Flow (TTM)',
  priceToSalesRate: 'Price to Sales Rate',
  priceToTangibleBookMRQ: 'Price to Tangible Book (MRQ)',
  quickRatioRate: 'Quick Ratio Rate',
  ratioLink: 'More Information',
  receivableTurnoverTTM: 'Receivable Turnover (TTM)',
  returnOnAssets5YA: 'Return on Assets (5-Year Avg)',
  returnOnAssetsRate: 'Return on Assets Rate',
  returnOnEquity5YA: 'Return on Equity (5-Year Avg)',
  returnOnEquityRate: 'Return on Equity Rate',
  returnOnInvestment5YA: 'Return on Investment (5-Year Avg)',
  returnOnInvestmentRate: 'Return on Investment Rate',
  revenueEmployeeTTM: 'Revenue per Employee (TTM)',
  revenueShareTTM: 'Revenue Share (TTM)',
  salesGrowthRate: 'Sales Growth Rate',
  salesMRQvsQtr1YrAgoMRQ: 'Sales (MRQ vs 1 Yr Ago MRQ)',
  tangibleBookValueShareMRQ: 'Tangible Book Value Share (MRQ)',
  updatedAt: 'Updated At',
  yearCapitalSpendingGrowth5YA: 'Year Capital Spending Growth (5-Year Avg)',
  yearEPSGrowth5YA: 'Year EPS Growth (5-Year Avg)',
  yearSalesGrowth5YA: 'Year Sales Growth (5-Year Avg)',
  industry: 'Industry',
  stockSymbol: 'Stock Symbol'
};

export default fakeRatioLabels;
