const constants = {
  HISTORICAL_DATA_FOR_ALL_STOCKS: 'HISTORICAL_DATA_FOR_ALL_STOCKS',
  ALL_STOCKS_CALCULATED: 'ALL_STOCKS_CALCULATED',
  ALL_STOCK_SYMBOLS: 'ALL_STOCK_SYMBOLS',
  CURRENT_PRICES: 'CURRENT_PRICES'
};

export default Object.freeze(constants);
