const Caching = {
  SP_500: 'S&P 500',
  BIST_ALL_SHARES:'BIST All Shares',
  ALL_STOCKS_CALCULATED:'ALL_STOCKS_CALCULATED',
  BIST_100_DETAILED_FINANCIALS: 'BIST100_DETAILED_FINANCIALS',
  SINGLE: 'SINGLE',
  SORTED_STOCKS: 'SORTED_STOCKS',
  UNSORTED_STOCKS: 'UNSORTED_STOCKS',
  BIST_100_SORTED: 'BISTHUNDSORT',
  BIST_100_UNSORTED: 'BISTHUNDUNSORTED',
  BIST100_SP500_FINANCIALS: 'BIST100_SP500_FINANCIALS',
  HISTORICAL_DATA_FOR_ALL_STOCKS:'HISTORICAL_DATA_FOR_ALL_STOCKS',
  VALUES: {
    INVESTING_SP500_VALUES_UNSORTED: 'INVESTING_SP500_VALUES_UNSORTED',
    INVESTING_SP500_VALUES_SORTED: 'INVESTING_SP500_VALUES_SORTED',
    INVESTING_BIST100_VALUES_UNSORTED: 'INVESTING_BIST100_VALUES_UNSORTED',
    INVESTING_BIST100_VALUES_SORTED: 'INVESTING_BIST100_VALUES_SORTED',
  },
  CALCULATIONS: {
    GRAHAM_NUMBERS: 'graham',
    PRICE_TO_EARNING_RATES: 'priceToEarningRates',
    PRICE_TO_BOOK_RATES: 'priceToBookRates',
    RETURN_ON_EQUITY_RATES: 'returnOnEquityRates',
    PRICE_TO_SALES_RATES: 'priceToSalesRates',
    DEBT_TO_EQUITY_RATES: 'debtToEquities',
    EBITDA: 'ebitdaValues',
    SYMBOL: 'symbol',
  },
  SYMBOLS: {
    SPFH: 'SPFIVEHUND_SYMBOLS',
    BISTHUND_SYMBOLS: 'BISTHUND_SYMBOLS',
    INVESTING_SP500: 'INVESTING_SP500',
    INVESTING_BIST100: 'INVESTING_BIST100',
    ALL_STOCK_SYMBOLS:'ALL_STOCK_SYMBOLS'
  },
  ROUTES:{
    INVESTING:{
      ALL_STOCK_ROUTES:'ALL_STOCK_ROUTES'
    }
  },
  NEWS: {
    FETCHED_OR_NOT: 'NEWS_FETCHED_OR_NOT',
  },
  PARAMETERS: 'parameters',
};

export default Caching;
