const investingCom = {
  COUNTRIES: {
    UNITED_STATES: "united-states",
    TURKEY: "turkey",
  },
  COUNTRIES_INTERIOR_CALLS:{
    UNITED_STATES:'UNITED_STATES',
    TURKEY:'TURKEY'
  },
  MARKETS: {
    SP_500: "S&P 500",
    BIST_100: "BIST 100",
    BIST_ALL_SHARES: "BIST All Shares",
  },
  MARKETS_INTERIOR_CALLS:{
      SP_500: "SP_500",
      BIST_100: "BIST_100",
      BIST_ALL_SHARES: "BIST_ALL_SHARES",
  },
  RATIO_URL_STOCK_PAIRS: {},
  INDUSTRY_MAPPING: {
    "Aerospace & Defense": "aerospaceAndDefense",
    "Automobiles & Auto Parts": "automobilesAndAutoParts",
    "Banking Services": "bankingServices",
    "Beverages": "beverages",
    "Biotechnology & Medical Research": "biotechnologyAndMedicalResearch",
    "Chemicals": "chemicals",
    "Coal": "coal",
    "Collective Investments": "collectiveInvestments",
    "Communications & Networking": "communicationsAndNetworking",
    "Computers, Phones & Household Electronics": "computersPhonesAndHouseholdElectronics",
    "Construction Materials": "constructionMaterials",
    "Construction & Engineering": "constructionAndEngineering",
    "Consumer Goods Conglomerates": "consumerGoodsConglomerates",
    "Containers & Packaging": "containersAndPackaging",
    "Diversified Industrial Goods Wholesale": "diversifiedIndustrialGoodsWholesale",
    "Diversified Retail": "diversifiedRetail",
    "Electrical Utilities & IPPs": "electricalUtilitiesAndIPPs",
    "Electronic Equipment & Parts": "electronicEquipmentAndParts",
    "Financial Technology (Fintech) & Infrastructure": "financialTechnologyAndInfrastructure",
    "Food & Drug Retailing": "foodAndDrugRetailing",
    "Food & Tobacco": "foodAndTobacco",
    "Freight & Logistics Services": "freightAndLogisticsServices",
    "Government Activity": "governmentActivity",
    "Healthcare Equipment & Supplies": "healthcareEquipmentAndSupplies",
    "Healthcare Providers & Services": "healthcareProvidersAndServices",
    "Homebuilding & Construction Supplies": "homebuildingAndConstructionSupplies",
    "Hotels & Entertainment Services": "hotelsAndEntertainmentServices",
    "Household Goods": "householdGoods",
    "Institutions, Associations & Organizations": "institutionsAssociationsAndOrganizations",
    "Insurance": "insurance",
    "Integrated Hardware & Software": "integratedHardwareAndSoftware",
    "Investment Banking & Investment Services": "investmentBankingAndInvestmentServices",
    "Investment Holding Companies": "investmentHoldingCompanies",
    "Leisure Products": "leisureProducts",
    "Machinery, Tools, Heavy Vehicles, Trains & Ships": "machineryToolsHeavyVehiclesTrainsAndShips",
    "Media & Publishing": "mediaAndPublishing",
    "Metals & Mining": "metalsAndMining",
    "Miscellaneous Educational Service Providers": "miscellaneousEducationalServiceProviders",
    "Multiline Utilities": "multilineUtilities",
    "Natural Gas Utilities": "naturalGasUtilities",
    "Office Equipment": "officeEquipment",
    "Oil & Gas": "oilAndGas",
    "Oil & Gas Related Equipment and Services": "oilAndGasRelatedEquipmentAndServices",
    "Paper & Forest Products": "paperAndForestProducts",
    "Passenger Transportation Services": "passengerTransportationServices",
    "Personal & Household Products & Services": "personalAndHouseholdProducts&Services",
    "Pharmaceuticals": "pharmaceuticals",
    "Professional & Business Education": "professionalAndBusinessEducation",
    "Professional & Commercial Services": "professionalAndCommercialServices",
    "Real Estate Operations": "realEstateOperations",
    "Renewable Energy": "renewableEnergy",
    "Residential & Commercial REITs": "residentialAndCommercialREITs",
    "School, College & University": "schoolCollegeAndUniversity",
    "Semiconductors & Semiconductor Equipment": "semiconductorsAndSemiconductorEquipment",
    "Software & IT Services": "softwareAndITServices",
    "Specialty Retailers": "specialtyRetailers",
    "Telecommunications Services": "telecommunicationsServices",
    "Textiles & Apparel": "textilesAndApparel",
    "Transport Infrastructure": "transportInfrastructure",
    "Uranium": "uranium",
    "Water & Related Utilities": "waterAndRelatedUtilities"
},
  KEY_MAPPING: {
    "P/E Ratio TTM": "priceToEarningRate",
    "Price to Sales TTM": "priceToSalesRate",
    "Price to Cash Flow MRQ": "priceToCashFlowMRQ",
    "Price to Free Cash Flow TTM": "priceToFreeCashFlowTTM",
    "Price to Book MRQ": "priceToBookRate",
    "Price to Tangible Book MRQ": "priceToTangibleBookMRQ",
    "Gross margin TTM": "grossMarginRate",
    "Gross Margin 5YA": "grossMargin5YA",
    "Operating margin TTM": "operatingMarginRate",
    "Operating margin 5YA": "operatingMargin5YA",
    "Pretax margin TTM": "pretaxMarginTTM",
    "Pretax margin 5YA": "pretaxMargin5YA",
    "Net Profit margin TTM": "netProfitMarginRate",
    "Net Profit margin 5YA": "netProfitMargin5YA",
    "Revenue/Share TTM": "revenueShareTTM",
    "Basic EPS ANN": "earningsPerShareRate",
    "Diluted EPS ANN": "dilutedEPSANN",
    "Book Value/Share MRQ": "bookValueShareMRQ",
    "Tangible Book Value/Share MRQ": "tangibleBookValueShareMRQ",
    "Cash/Share MRQ": "cashShareMRQ",
    "Cash Flow/Share TTM": "cashFlowShareTTM",
    "Return on Equity TTM": "returnOnEquityRate",
    "Return on Equity 5YA": "returnOnEquity5YA",
    "Return on Assets TTM": "returnOnAssetsRate",
    "Return on Assets 5YA": "returnOnAssets5YA",
    "Return on Investment TTM": "returnOnInvestmentRate",
    "Return on Investment 5YA": "returnOnInvestment5YA",
    "EPS(MRQ) vs Qtr. 1 Yr. Ago MRQ": "ePSMRQvsQtr1YrAgoMRQ",
    "EPS(TTM) vs TTM 1 Yr. Ago TTM": "ePSTTMvsTTM1YrAgoTTM",
    "5 Year EPS Growth 5YA": "yearEPSGrowth5YA",
    "Sales (MRQ) vs Qtr. 1 Yr. Ago MRQ": "salesMRQvsQtr1YrAgoMRQ",
    "Sales (TTM) vs TTM 1 Yr. Ago TTM": "salesGrowthRate",
    "5 Year Sales Growth 5YA": "yearSalesGrowth5YA",
    "5 Year Capital Spending Growth 5YA": "yearCapitalSpendingGrowth5YA",
    "Quick Ratio MRQ": "quickRatioRate",
    "Current Ratio MRQ": "currentRatioRate",
    "LT Debt to Equity MRQ": "lTDebtToEquityMRQ",
    "Total Debt to Equity MRQ": "debtToEquityRate",
    "Asset Turnover TTM": "assetTurnoverTTM",
    "Inventory Turnover TTM": "inventoryTurnoverTTM",
    "Revenue/Employee TTM": "revenueEmployeeTTM",
    "Net Income/Employee TTM": "netIncomeEmployeeTTM",
    "Receivable Turnover TTM": "receivableTurnoverTTM",
    "Dividend Yield ANN": "returnOnInvestmentRate",
    "Dividend Yield 5 Year Avg. 5YA": "dividendYield5YearAvg5YA",
    "Dividend Growth Rate ANN": "dividendGrowthRateANN",
    "Payout Ratio TTM": "payoutRatioTTM",
  },
  findKeyByValue(object, value){
    return Object.keys(object).find(key=> object[key]===value);
  }
};

export default investingCom;
